name: pyswitcher_app
description: A mobile client for PySwitcherIO devices
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2
  shared_preferences: ^2.0.15
  permission_handler: ^12.0.1

flutter:
  uses-material-design: true

# If permission_handler_android from pub.dev still contains v1 embedding
# references, use the git version from the official repo as an override.
# This forces the plugin platform implementation to the latest source.
dependency_overrides:
  permission_handler_android:
    git:
      url: https://github.com/Baseflow/flutter-permission-handler.git
      path: permission_handler_android
      ref: main
